// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdjn21_BkVnQB5pL_Wg9v0G3kwl-4gdKI',
    appId: '1:249772049184:web:6273d019c0bfc7d92e8d45',
    messagingSenderId: '249772049184',
    projectId: 'map-test-de3c1',
    authDomain: 'map-test-de3c1.firebaseapp.com',
    storageBucket: 'map-test-de3c1.appspot.com',
    measurementId: 'G-46EDD3CTE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeHGcTnkfMSFa2e6JDlCZlrGwKkyiqllI',
    appId: '1:249772049184:android:d655056ae4d8b58c2e8d45',
    messagingSenderId: '249772049184',
    projectId: 'map-test-de3c1',
    storageBucket: 'map-test-de3c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTIhm4QkYxCS6DZZsW7COOX7pC9Gstu60',
    appId: '1:249772049184:ios:2242004ba0adb89a2e8d45',
    messagingSenderId: '249772049184',
    projectId: 'map-test-de3c1',
    storageBucket: 'map-test-de3c1.appspot.com',
    iosClientId: '249772049184-4lj7frbbk2e7j0rpcdtsa1itj6rghkil.apps.googleusercontent.com',
    iosBundleId: 'com.example.maptest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTIhm4QkYxCS6DZZsW7COOX7pC9Gstu60',
    appId: '1:249772049184:ios:2242004ba0adb89a2e8d45',
    messagingSenderId: '249772049184',
    projectId: 'map-test-de3c1',
    storageBucket: 'map-test-de3c1.appspot.com',
    iosClientId: '249772049184-4lj7frbbk2e7j0rpcdtsa1itj6rghkil.apps.googleusercontent.com',
    iosBundleId: 'com.example.maptest',
  );
}
